changelog:
  exclude:
    labels:
      - ignore-for-release

  categories:
    - title: Breaking Changes
      labels:
        - breaking-change

    - title: Bug Fixes
      labels:
        - bug

    - title: Enhancements
      labels:
        - enhancement

    - title: Performance
      labels:
        - performance

    - title: Maintenance
      labels:
        - chore
        - refactor
        - area:build

    - title: Protocol and API Changes
      labels:
        - area:http
        - area:jms
        - area:api

    - title: Documentation
      labels:
        - documentation

    - title: Dependencies
      labels:
        - dependencies

    - title: Other Changes
      labels:
        - "*"
