package com.echo.config;

import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.boot.ApplicationArguments;
import org.springframework.boot.ApplicationRunner;
import org.springframework.core.annotation.Order;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Component;

import javax.sql.DataSource;

/**
 * H2 schema 遷移：修復 responses.id 從 SEQUENCE 改為 IDENTITY 後的相容性問題。
 * <p>
 * 背景：Response entity 的 ID 策略從 SEQUENCE 改為 IDENTITY（為支援 SQLite），
 * 但 ddl-auto=update 不會修改既有欄位的 auto-increment 設定，
 * 導致 Hibernate 插入時使用 `default` 關鍵字而欄位沒有 IDENTITY 屬性。
 * <p>
 * 此元件在啟動時檢查並自動修復，僅對 H2 資料庫生效。
 */
@Component
@Order(1)
@RequiredArgsConstructor
@Slf4j
public class H2SchemaMigration implements ApplicationRunner {

    private final DataSource dataSource;
    private final JdbcTemplate jdbcTemplate;

    @Override
    public void run(ApplicationArguments args) {
        if (!isH2()) {
            return;
        }

        migrateResponsesId();
    }

    private void migrateResponsesId() {
        Boolean isIdentity = jdbcTemplate.queryForObject(
                "SELECT IS_IDENTITY FROM INFORMATION_SCHEMA.COLUMNS " +
                        "WHERE TABLE_NAME = 'RESPONSES' AND COLUMN_NAME = 'ID'",
                Boolean.class);

        if (Boolean.TRUE.equals(isIdentity)) {
            return;
        }

        log.info("Migrating responses.id to IDENTITY...");

        Long maxId = jdbcTemplate.queryForObject("SELECT COALESCE(MAX(id), 0) FROM responses", Long.class);

        jdbcTemplate.execute("ALTER TABLE responses ALTER COLUMN id BIGINT GENERATED BY DEFAULT AS IDENTITY");
        jdbcTemplate.execute("ALTER TABLE responses ALTER COLUMN id RESTART WITH " + (maxId + 1));

        log.info("Migration complete. responses.id IDENTITY restarts at {}", maxId + 1);
    }

    private boolean isH2() {
        try (var conn = dataSource.getConnection()) {
            String url = conn.getMetaData().getURL();
            return url != null && url.startsWith("jdbc:h2:");
        } catch (Exception e) {
            return false;
        }
    }
}
