name: Manage labels

on:
  schedule:
    - cron: "30 20 * * *"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  labeler:
    name: Sync labels
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Check out the repository
        uses: actions/checkout@v6

      - name: Run Labeler
        uses: crazy-max/ghaction-github-labeler@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          yaml-file: .github/labels.yml
          skip-delete: true
